<?php

namespace LastBundle\Repository;

/**
 * FullCalendarListenerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FullCalendarListenerRepository extends \Doctrine\ORM\EntityRepository
{
}
