main_reclamation:
    resource: "@MainBundle/Resources/config/routing/reclamation.yml"
    prefix:   /reclamation
main_feedback:
    resource: "@MainBundle/Resources/config/routing/feedback.yml"
    prefix:   /feedback




main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }
