<?php

namespace FormationBundle\Repository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByDescription($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e
                FROM FormationBundle:Formation e
                WHERE e.description LIKE :str OR e.nom LIKE :str OR e.lieu LIKE :str '
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
}
