feedback_index:
    path:     /
    defaults: { _controller: "MainBundle:Feedback:index" }
    methods:  GET

feedback_show:
    path:     /{id7}/show
    defaults: { _controller: "MainBundle:Feedback:show" }
    methods:  GET

feedback_new:
    path:     /new
    defaults: { _controller: "MainBundle:Feedback:new" }
    methods:  [GET, POST]

feedback_edit:
    path:     /{id7}/edit
    defaults: { _controller: "MainBundle:Feedback:edit" }
    methods:  [GET, POST]

feedback_delete:
    path:     /{id7}/delete
    defaults: { _controller: "MainBundle:Feedback:delete" }
    methods:  DELETE
