actualite:
    resource: "@ActualiteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Resources/config/routing.yml'
    #type: annotation


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type: annotation
    prefix: /easyadmin