main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /



app:
    resource: '@AppBundle/Resources/config/routing.yml'
    #type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"