actualite:
    resource: "@ActualiteBundle/Resources/config/routing.yml"
    prefix:   /

last:
    resource: "@LastBundle/Resources/config/routing.yml"
    prefix:   /event

app:
    resource: '@AppBundle/Resources/config/routing.yml'
    #type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
toiba_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yaml"

main:
  resource: "@MainBundle/Resources/config/routing.yml"
  prefix:   /main


projet:
  resource: "@ProjetBundle/Resources/config/routing.yml"
  prefix:   /projet

formation:
  resource: "@FormationBundle/Resources/config/routing.yml"
  prefix:   /Formation
