<?php

namespace ActualiteBundle\Repository;

/**
 * ActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteRepository extends \Doctrine\ORM\EntityRepository
{
    public function listeractualite(){
        $query=$this->getEntityManager()
            ->createQuery("SELECT e FROM ActualiteBundle:Actualite e
                                where  e.etat = :d")
            ->setParameter('d',0);

        return $query->getResult();
    }
}
